// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.feature.impl.rift;

import com.vertexai.Vertex;
import com.vertexai.util.KeyBindUtil;
import com.vertexai.util.Logger;
import com.vertexai.util.UseItemAbility;
import com.vertexai.util.helper.Clock;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Minecraft;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.*;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class VampireSlayerTracker {
    private static final String BLOODFIEND_NAME = "Bloodfiend";
    private static final String[] NAME_START = {"§c☠ §4Bloodfiend"};
    private static final Pattern TIMER_PATTERN = Pattern.compile("(?:§[8bef]§l(ASHEN|CRYSTAL|AURIC|SPIRIT)§[8bef] ♨\\d |§4§lIMMUNE )?§c\\d+:\\d+(?:§r)?");
    private static final Pattern IMPEL_PATTERN = Pattern.compile("Impel\\s*:?\\s*(.+?)\\s+([0-9]+(?:\\.[0-9]+)?)s\\b", Pattern.CASE_INSENSITIVE);
    private static final Pattern TWINCLAWS_PATTERN = Pattern.compile("TWINCLAWS (\\d(?:\\.\\d)?)s");
    private static final String HOLY_ICE_ID = "HOLY_ICE";
    private static final String STEAK_STAKE_ID = "STEAK_STAKE";
    private static final String[] SUPER_SHARP_STAKE_IDS = {"SUPER_SHARP_STEAK_STAKE", "SUPER_SHARP_STABBY_STEAK_STAKE", "SHARP_STEAK_STAKE"};
    private static final HealingItem[] HEALING_ITEMS = {new HealingItem("HEALING_MELON", "Healing Melon", 7), new HealingItem("JUICY_HEALING_MELON", "Juicy Healing Melon", 9), new HealingItem("LUSCIOUS_HEALING_MELON", "Luscious Healing Melon", 12)};
    private static final float PANIC_HEARTS = 2.0F;
    private static final int MIN_HEAL_DELAY_MS = 600;
    private static final int MAX_HEAL_DELAY_MS = 1000;
    private static final int MIN_IMPEL_DELAY_MS = 90;
    private static final int MAX_IMPEL_DELAY_MS = 180;
    private static final int MIN_KEY_HOLD_MS = 80;
    private static final int MAX_KEY_HOLD_MS = 140;
    private static final int MIN_HOLY_ICE_DELAY_MS = 1400;
    private static final int MAX_HOLY_ICE_DELAY_MS = 2000;
    private static final int LOCATE_BLOODFIEND_COOLDOWN_MS = 500;
    private static final float MIN_UP_PITCH = -85.0F;
    private static final float MAX_UP_PITCH = -60.0F;
    private static final float MIN_DOWN_PITCH = 60.0F;
    private static final float MAX_DOWN_PITCH = 85.0F;
    private static final int MIN_CLICK_AFTER_LOOK_MS = 40;
    private static final int MAX_CLICK_AFTER_LOOK_MS = 90;
    private static final double HOLY_ICE_TRIGGER_SECONDS = 0.5;
    private static final VampireSlayerTracker instance = new VampireSlayerTracker();
    private static final Minecraft mc = Minecraft.getInstance();
    private final Clock scanTimer = new Clock();
    private final Clock locateCooldown = new Clock();
    private final Clock healCooldown = new Clock();
    private final Clock impelCooldown = new Clock();
    private final Clock swapCooldown = new Clock();
    private final Clock holyIceCooldown = new Clock();
    private Player bloodfiendEntity;
    private ArmorStand nameEntity;
    private ArmorStand timerEntity;
    private boolean stakeable;
    private boolean twinclawsActive;
    private String lastImpelAction;
    private long lastImpelActionTime;
    private double lastImpelSeconds;
    private boolean impelHandled;
    private boolean lastStakeable;
    private boolean lastTwinclawsActive;
    private boolean missingHolyIceLogged;
    private boolean missingStakeLogged;
    private double twinclawsSeconds = -1.0;

    public void onTick() {
        if (mc.level == null || mc.player == null) {
            return;
        }
        if (Vertex.config().rift.riftAutoHeal) {
            attemptHealing();
        }
        if (bloodfiendEntity != null && !bloodfiendEntity.isAlive()) {
            Logger.sendMessage("[Rift] Bloodfiend despawned.");
            resetTracking();
            return;
        }
        if (bloodfiendEntity == null) {
            attemptLocateBloodfiend();
            if (bloodfiendEntity == null && needsRescan()) {
                scanForArmorStands();
            }
            if (bloodfiendEntity == null && nameEntity == null && timerEntity == null) {
                return;
            }
        }
        if (Vertex.config().rift.riftAutoHolyIce) {
            attemptHolyIce();
        }
        if (Vertex.config().rift.riftAutoStakeSwap) {
            attemptStakeSwap();
        }
        if (needsRescan()) {
            scanForArmorStands();
        }
    }

    public void onEntityUpdate(Player entity, byte updateType) {
        handlePotentialBloodfiend(entity, updateType);
    }

    public void onEntityUpdate(ArmorStand stand, byte updateType) {
        handleArmorStandUpdate(stand, updateType);
    }

    public void onWorldUnload() {
        resetTracking();
    }

    public void onPacketReceive(Packet<?> packet) {
        if (!Vertex.config().rift.riftEnabled || bloodfiendEntity == null || !Vertex.config().rift.riftAutoImpel) {
            return;
        }
        String message = extractImpelMessage(packet);
        if (message == null || message.trim().isEmpty()) {
            return;
        }
        java.util.regex.Matcher matcher = IMPEL_PATTERN.matcher(message.trim());
        if (!matcher.find()) {
            return;
        }
        String action = matcher.group(1).trim();
        ImpelAction impelAction = parseImpelAction(action);
        if (impelAction == null) {
            return;
        }
        long now = System.currentTimeMillis();
        String actionKey = impelAction.getName();
        if (actionKey.equals(lastImpelAction) && impelHandled) {
            return;
        }
        lastImpelAction = actionKey;
        lastImpelActionTime = now;
        try {
            lastImpelSeconds = Double.parseDouble(matcher.group(2));
        } catch (NumberFormatException ignored) {
            lastImpelSeconds = 0.0;
        }
        impelHandled = false;
        Logger.sendMessage("[Rift] Impel: " + impelAction.getDisplayName() + ".");
        performImpelAction(impelAction);
    }

    private String extractImpelMessage(Packet<?> packet) {
        if (packet instanceof ClientboundSetTitleTextPacket) {
            return stripFormatting(((ClientboundSetTitleTextPacket) packet).text().getString());
        }
        if (packet instanceof ClientboundSetSubtitleTextPacket) {
            return stripFormatting(((ClientboundSetSubtitleTextPacket) packet).text().getString());
        }
        if (packet instanceof ClientboundSetActionBarTextPacket) {
            return stripFormatting(((ClientboundSetActionBarTextPacket) packet).text().getString());
        }
        if (packet instanceof ClientboundSystemChatPacket) (ERROR);
        if (!overlay) {
            return null;
        }
        return stripFormatting(content.getString());
    }

    (ERROR) <error>(packet <error>);

    chatPacket <error>;

    {
        return stripFormatting(chatPacket.body().content());
    }

    (ERROR) <error>;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static VampireSlayerTracker getInstance() {
        return VampireSlayerTracker.instance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Player getBloodfiendEntity() {
        return this.bloodfiendEntity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ArmorStand getNameEntity() {
        return this.nameEntity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public ArmorStand getTimerEntity() {
        return this.timerEntity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isStakeable() {
        return this.stakeable;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isTwinclawsActive() {
        return this.twinclawsActive;
    }
}
(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)
class <error> {
    bloodfiendEntity.getBoundingAABB <error>();

    ArmorStand candidateName = null;
    ArmorStand candidateTimer = null;
    boolean foundTwinclaws = false;

    (ERROR) <error>(ArmorStand stand);

    stands <error>;

    {
        String tag = getCustomNameTag(stand);
        if (tag == null || tag.trim().isEmpty()) {
            continue;
        }
        String strippedTag = stripFormatting(tag);
        boolean potentialStand = isPotentialNameStand(stand);
        boolean bloodfiendName = isBloodfiendName(tag);
        Matcher twinclawsMatcher = TWINCLAWS_PATTERN.matcher(strippedTag);
        boolean hasTwinclaws = twinclawsMatcher.find();
        boolean isTimer = TIMER_PATTERN.matcher(tag).matches();
        if (!potentialStand && !bloodfiendName && !hasTwinclaws && !isTimer) {
            continue;
        }
        if (hasTwinclaws) {
            foundTwinclaws = true;
            twinclawsActive = true;
            try {
                twinclawsSeconds = Double.parseDouble(twinclawsMatcher.group(1));
            } catch (NumberFormatException ignored) {
                twinclawsSeconds = -1.0;
            }
            logTwinclawsChange(true);
        }
        if (candidateName == null && bloodfiendName) {
            candidateName = stand;
            continue;
        }
        if (candidateTimer == null && isTimer) {
            candidateTimer = stand;
        }
    }

    (ERROR) <error>(candidateName <error>);

    (ERROR) <error>;
    (ERROR) candidateName;

    <error>(getCustomNameTag <error>);

    (ERROR) <error>;
}
(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)
enum ImpelAction {
    JUMP("Jump"), SNEAK("Sneak"), CLICK_UP("Click Up"), CLICK_DOWN("Click Down"), CLICK("Click");
    private final String displayName;

    ImpelAction(String displayName) {
        this.displayName = displayName;
    }

    private String getDisplayName() {
        return displayName;
    }
}
(ERROR)