// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.client.overlay;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphics;

public abstract class AbstractHUDElement {
    protected float x = 5;
    protected float y = 5;
    protected boolean enabled = true;
    protected float scale = 1.0F;
    // 0: Top-Left, 1: Top-Right, 2: Bottom-Left, 3: Bottom-Right
    protected int anchor = 0;
    protected Minecraft mc = Minecraft.getInstance();

    public abstract void render(GuiGraphics context, float tickDelta);

    /**
     * Render variant used by the HUD editor.
     * Defaults to normal rendering.
     */
    public void renderForEditor(GuiGraphics context, float tickDelta) {
        render(context, tickDelta);
    }

    public abstract int getWidth();

    public abstract int getHeight();

    /**
     * Size variant used by the HUD editor.
     * Defaults to normal size.
     */
    public int getEditorWidth() {
        return getWidth();
    }

    /**
     * Size variant used by the HUD editor.
     * Defaults to normal size.
     */
    public int getEditorHeight() {
        return getHeight();
    }

    public float getActualX(int elementWidth) {
        int screenWidth = mc.getWindow().getGuiScaledWidth();
        float raw = (ERROR);
        (ERROR);
        {
        }
        ;
        float maxX = Math.max(0, screenWidth - elementWidth);
        return Math.max(0, Math.min(raw, maxX));
    }

    public float getActualY(int elementHeight) {
        int screenHeight = mc.getWindow().getGuiScaledHeight();
        float raw = (ERROR);
        (ERROR);
        {
        }
        ;
        float maxY = Math.max(0, screenHeight - elementHeight);
        return Math.max(0, Math.min(raw, maxY));
    }

    public float getActualX() {
        return getActualX(getWidth());
    }

    public float getActualY() {
        return getActualY(getHeight());
    }

    public boolean isHovered(double mouseX, double mouseY) {
        return isHovered(mouseX, mouseY, getWidth(), getHeight());
    }

    public boolean isHovered(double mouseX, double mouseY, int width, int height) {
        float ax = getActualX(width);
        float ay = getActualY(height);
        return mouseX >= ax && mouseX <= ax + width && mouseY >= ay && mouseY <= ay + height;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getX() {
        return this.x;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setX(final float x) {
        this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getY() {
        return this.y;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setY(final float y) {
        this.y = y;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean isEnabled() {
        return this.enabled;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getScale() {
        return this.scale;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setScale(final float scale) {
        this.scale = scale;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getAnchor() {
        return this.anchor;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setAnchor(final int anchor) {
        this.anchor = anchor;
    }
}
