// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.feature.impl.AutoDrillRefuel;

import com.vertexai.failsafe.AbstractFailsafe.Failsafe;
import com.vertexai.feature.AbstractFeature;
import com.vertexai.feature.impl.AutoDrillRefuel.states.AutoDrillRefuelState;
import com.vertexai.feature.impl.AutoDrillRefuel.states.StartingState;

public class AutoDrillRefuel extends AbstractFeature {
    private static final AutoDrillRefuel instance = new AutoDrillRefuel();
    private AutoDrillRefuelError error = AutoDrillRefuelError.NONE;
    private FuelType fuelType;
    private String drillName;
    private AutoDrillRefuelState currentState;

    @Override
    public String getName() {
        return "AutoDrillRefuel";
    }

    @Override
    public void resetStatesAfterStop() {
        this.failsafesToIgnore.remove(Failsafe.ITEM_CHANGE);
    }

    public void start(String drillName, FuelType fuelType) {
        this.enabled = true;
        this.drillName = drillName;
        this.fuelType = fuelType;
        this.error = AutoDrillRefuelError.NONE;
        currentState = new StartingState();
    }

    @Override
    public void stop() {
        super.stop();
    }

    @Override
    protected void onTick() {
        if (!this.enabled) {
            return;
        }
        if (currentState == null) return;
        AutoDrillRefuelState nextState = currentState.onTick(this);
        transitionTo(nextState);
    }

    private void transitionTo(AutoDrillRefuelState nextState) {
        // Skip if no state change
        if (currentState == nextState) return;
        currentState.onEnd(this);
        currentState = nextState;
        if (currentState == null) {
            log("null state, returning");
            return;
        }
        currentState.onStart(this);
    }


    public enum AutoDrillRefuelError {
        NONE, NO_DRILL, NO_FUEL, NO_ABIPHONE, NO_GREATFORGE_CONTACT;
    }


    public enum FuelType {
        VOLTA("Volta"), OIL_BARREL("Oil Barrel"), SUNFLOWER_OIL("Sunflower Oil");
        private final String name;

        FuelType(String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public String getName() {
            return this.name;
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static AutoDrillRefuel getInstance() {
        return AutoDrillRefuel.instance;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setError(final AutoDrillRefuelError error) {
        this.error = error;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public AutoDrillRefuelError getError() {
        return this.error;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public FuelType getFuelType() {
        return this.fuelType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDrillName() {
        return this.drillName;
    }
}
