// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.event;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

/**
 * Event fired before sending player movement packets to server.
 * Allows modifying the yaw/pitch that gets sent.
 */
public class MotionUpdateEvent {
    private static final List<Consumer<MotionUpdateEvent>> listeners = new ArrayList<>();
    public float yaw;
    public float pitch;

    public static void register(Consumer<MotionUpdateEvent> listener) {
        listeners.add(listener);
    }

    public static void fire(MotionUpdateEvent event) {
        for (Consumer<MotionUpdateEvent> listener : listeners) {
            listener.accept(event);
        }
    }

    public void setYaw(float yaw) {
        this.yaw = yaw;
    }

    public void setPitch(float pitch) {
        this.pitch = pitch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getYaw() {
        return this.yaw;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float getPitch() {
        return this.pitch;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public MotionUpdateEvent(final float yaw, final float pitch) {
        this.yaw = yaw;
        this.pitch = pitch;
    }
}
