// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.event;

import net.minecraft.core.particles.ParticleType;
import net.minecraft.world.phys.Vec3;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;

/**
 * Event fired when a particle spawns.
 */
public class SpawnParticleEvent {
   private static final List<Consumer<SpawnParticleEvent>> listeners = new ArrayList<>();
   private final ParticleType<?> particleType;
   private final boolean longDistance;
   private final double x;
   private final double y;
   private final double z;
   private final double velocityX;
   private final double velocityY;
   private final double velocityZ;
   private boolean cancelled = false;

   public SpawnParticleEvent(ParticleType<?> particleType, boolean longDistance, double x, double y, double z, double velocityX, double velocityY, double velocityZ) {
      this.particleType = particleType;
      this.longDistance = longDistance;
      this.x = x;
      this.y = y;
      this.z = z;
      this.velocityX = velocityX;
      this.velocityY = velocityY;
      this.velocityZ = velocityZ;
   }

   public static void register(Consumer<SpawnParticleEvent> listener) {
      listeners.add(listener);
   }

   public static SpawnParticleEvent fire(ParticleType<?> particleType, boolean longDistance, double x, double y, double z, double velocityX, double velocityY, double velocityZ) {
      SpawnParticleEvent event = new SpawnParticleEvent(particleType, longDistance, x, y, z, velocityX, velocityY, velocityZ);
      for (Consumer<SpawnParticleEvent> listener : listeners) {
         listener.accept(event);
      }
      return event;
   }

   public ParticleType<?> getParticleType() {
      return this.particleType;
   }

   public Vec3 getPos() {
      return new Vec3(x, y, z);
   }

   public boolean isCancelled() {
      return this.cancelled;
   }

   public void cancel() {
      this.cancelled = true;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public boolean isLongDistance() {
      return this.longDistance;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getX() {
      return this.x;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getY() {
      return this.y;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getZ() {
      return this.z;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getVelocityX() {
      return this.velocityX;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getVelocityY() {
      return this.velocityY;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public double getVelocityZ() {
      return this.velocityZ;
   }
}
