// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.feature.impl;

import com.vertexai.feature.AbstractFeature;

public class AutoSell extends AbstractFeature {
    public static AutoSell instance = new AutoSell();

    @Override
    public String getName() {
        return "AutoSell";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static AutoSell getInstance() {
        return AutoSell.instance;
    }
}
