// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.feature.impl;

import com.vertexai.feature.AbstractFeature;

public class WorldScanner extends AbstractFeature {
    public static WorldScanner instance = new WorldScanner();

    @Override
    public String getName() {
        return "WorldScanner";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static WorldScanner getInstance() {
        return WorldScanner.instance;
    }
}
