// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.failsafe.impl;

import com.vertexai.failsafe.AbstractFailsafe;
import com.vertexai.macro.MacroManager;
import net.minecraft.client.gui.screens.DisconnectedScreen;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.common.ClientboundDisconnectPacket;

public class DisconnectFailsafe extends AbstractFailsafe {
    private static final DisconnectFailsafe instance = new DisconnectFailsafe();

    @Override
    public String getName() {
        return "DisconnectFailsafe";
    }

    @Override
    public Failsafe getFailsafeType() {
        return Failsafe.DISCONNECT;
    }

    @Override
    public int getPriority() {
        return 10;
    }

    @Override
    public boolean onPacketReceive(Packet<?> packet) {
        return packet instanceof ClientboundDisconnectPacket || mc.gui.screen() instanceof DisconnectedScreen;
    }

    @Override
    public boolean react() {
        warn("Disconnected. Disabling Macro");
        MacroManager.getInstance().disable();
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static DisconnectFailsafe getInstance() {
        return DisconnectFailsafe.instance;
    }
}
