// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.failsafe.impl;

import com.vertexai.Vertex;
import com.vertexai.failsafe.AbstractFailsafe;
import com.vertexai.macro.MacroManager;
import com.vertexai.util.Logger;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.ClientboundSetEntityMotionPacket;

public class KnockbackFailsafe extends AbstractFailsafe {
    private static final KnockbackFailsafe instance = new KnockbackFailsafe();

    public int getPriority() {
        return 8;
    }

    @Override
    public String getName() {
        return "";
    }

    @Override
    public Failsafe getFailsafeType() {
        return Failsafe.KNOCKBACK;
    }

    @Override
    public boolean onPacketReceive(Packet<?> packet) {
        if (!(packet instanceof ClientboundSetEntityMotionPacket)) (ERROR);
        minecraft.world.phys.Vec3 movement;
        return false;
        if (id != mc.player.getId()) return false;
        return movement.y >= Vertex.config().failsafe.verticalKnockbackThreshold;
    }

    @Override
    public boolean react() {
        MacroManager.getInstance().disable();
        Logger.sendWarning("Knockback has been detected! Disabling macro.");
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static KnockbackFailsafe getInstance() {
        return KnockbackFailsafe.instance;
    }
}
