// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.failsafe.impl;

import com.vertexai.failsafe.AbstractFailsafe;
import com.vertexai.macro.MacroManager;
import com.vertexai.util.Logger;
import com.vertexai.util.helper.Clock;
import net.minecraft.client.Minecraft;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.ClientboundSetHeldSlotPacket;

public class SlotChangeFailsafe extends AbstractFailsafe {
    private static final SlotChangeFailsafe instance = new SlotChangeFailsafe();
    private final Minecraft mc = Minecraft.getInstance();
    private final Clock timer = new Clock();
    private int lastSelectedSlot;
    private boolean slotChanged = false;

    private SlotChangeFailsafe() {
        this.lastSelectedSlot = mc.player != null ? mc.player.getInventory().getSelectedSlot() : -1;
    }

    @Override
    public String getName() {
        return "SlotChangeFailsafe";
    }

    @Override
    public Failsafe getFailsafeType() {
        return Failsafe.SLOT_CHANGE;
    }

    @Override
    public int getPriority() {
        return 5;
    }

    @Override
    public boolean onTick() {
        if (slotChanged && timer.passed()) {
            Logger.sendLog("Timer passed after slot change");
            return true;
        }
        return false;
    }

    @Override
    public boolean onPacketReceive(Packet<?> packet) {
        if (packet instanceof ClientboundSetHeldSlotPacket) (ERROR);
        if (slotIndex != lastSelectedSlot) {
            log("Slot changed by S09 packet from " + lastSelectedSlot + " to " + slotIndex);
            slotChanged = true;
            lastSelectedSlot = slotIndex;
            if (!timer.isScheduled()) {
                timer.schedule(2000);
            }
        }
    }

    (ERROR) <error>;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static SlotChangeFailsafe getInstance() {
        return SlotChangeFailsafe.instance;
    }
}
(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)(ERROR)