// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.failsafe.impl;

import com.vertexai.failsafe.AbstractFailsafe;
import com.vertexai.feature.impl.LagDetector;
import com.vertexai.macro.MacroManager;
import com.vertexai.util.Logger;
import com.vertexai.util.helper.Clock;
import net.minecraft.client.Minecraft;
import net.minecraft.network.protocol.Packet;
import net.minecraft.network.protocol.game.ClientboundPlayerPositionPacket;
import net.minecraft.world.entity.Relative;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.phys.Vec3;

public class TeleportFailsafe extends AbstractFailsafe {
    private static final TeleportFailsafe instance = new TeleportFailsafe();
    private final LagDetector lagDetector = LagDetector.getInstance();
    private final Minecraft mc = Minecraft.getInstance();
    private final Clock triggerCheck = new Clock();
    private Vec3 originalPosition = null;
    private boolean potentialTeleportDetected = false;

    @Override
    public String getName() {
        return "TeleportFailsafe";
    }

    @Override
    public Failsafe getFailsafeType() {
        return Failsafe.TELEPORT;
    }

    @Override
    public int getPriority() {
        return 5;
    }

    @Override
    public boolean react() {
        Logger.sendWarning("You have been teleported");
        MacroManager.getInstance().disable();
        reset();
        return true;
    }

    @Override
    public boolean onPacketReceive(Packet<?> packet) {
        if (!(packet instanceof ClientboundPlayerPositionPacket)) (ERROR);
        {
            return false;
        }
        Vec3 currentPlayerPos = mc.player.position();
        Vec3 packetPlayerPos = new Vec3(p.change().position().x + (p.relatives().contains(Relative.X) ? currentPlayerPos.x : 0), p.change().position().y + (p.relatives().contains(Relative.Y) ? currentPlayerPos.y : 0), p.change().position().z + (p.relatives().contains(Relative.Z) ? currentPlayerPos.z : 0));
        double distance = currentPlayerPos.distanceTo(packetPlayerPos);
        if (distance >= 1) {
            final double lastReceivedPacketDistance = currentPlayerPos.distanceTo(lagDetector.getLastPacketPosition());
            final double playerMovementSpeed = mc.player.getAttributes().getValue(Attributes.MOVEMENT_SPEED);
            final int ticksSinceLastPacket = (int) Math.ceil(lagDetector.getTimeSinceLastTick() / 50.0);
            final double estimatedMovement = playerMovementSpeed * ticksSinceLastPacket;
            if (lastReceivedPacketDistance > 7.5 && Math.abs(lastReceivedPacketDistance - estimatedMovement) < 2) {
                return false;
            }
            if (originalPosition == null) {
                originalPosition = currentPlayerPos;
            }
            potentialTeleportDetected = true;
            triggerCheck.schedule(500);
            return false;
        }
        return false;
    }

    @Override
    public boolean onTick() {
        if (potentialTeleportDetected && triggerCheck.isScheduled() && triggerCheck.passed()) {
            triggerCheck.reset();
            potentialTeleportDetected = false;
            Vec3 currentPosition = mc.player.position();
            if (originalPosition != null) {
                double totalDisplacement = currentPosition.distanceTo(originalPosition);
                originalPosition = null;
                return totalDisplacement > 1;
            }
        }
        return false;
    }

    public void reset() {
        originalPosition = null;
        potentialTeleportDetected = false;
        triggerCheck.reset();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static TeleportFailsafe getInstance() {
        return TeleportFailsafe.instance;
    }
}
