// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.util.helper;

import net.minecraft.client.Minecraft;
import java.util.Optional;
import java.util.Random;
import java.util.function.Function;

public class RotationConfiguration {
    private final Minecraft mc = Minecraft.getInstance();
    private Optional<Angle> from = Optional.empty();
    private Optional<Angle> to = Optional.empty();
    private Optional<Target> target;
    private Optional<Runnable> callback;
    private long time;
    private boolean easeBackToClientSide = false;
    private boolean followTarget = false;
    private RotationType rotationType = RotationType.CLIENT;
    private Ease easeFunction = Ease.values()[new Random().nextInt(Ease.values().length - 1)];
    private boolean randomness = false;

    public RotationConfiguration(Angle from, Angle to, long time, RotationType rotationType, Runnable callback) {
        this.from = Optional.of(from);
        this.to = Optional.ofNullable(to);
        this.target = Optional.of(new Target(to));
        this.time = time;
        this.rotationType = rotationType;
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration(Angle from, Target target, long time, RotationType rotationType, Runnable callback) {
        this.from = Optional.of(from);
        this.time = time;
        this.target = Optional.ofNullable(target);
        this.rotationType = rotationType;
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration(Angle to, long time, Runnable callback) {
        this.to = Optional.ofNullable(to);
        this.target = Optional.of(new Target(to));
        this.time = time;
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration(Angle to, long time, RotationType rotationType, Runnable callback) {
        this.to = Optional.ofNullable(to);
        this.target = Optional.of(new Target(to));
        this.time = time;
        this.rotationType = rotationType;
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration(Target target, long time, Runnable callback) {
        this.time = time;
        this.target = Optional.ofNullable(target);
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration(Target target, long time, RotationType rotationType, Runnable callback) {
        this.time = time;
        this.target = Optional.ofNullable(target);
        this.rotationType = rotationType;
        this.callback = Optional.ofNullable(callback);
    }

    public RotationConfiguration setTarget(final Target target) {
        this.target = Optional.of(target);
        return this;
    }

    public RotationConfiguration easeFunction(Ease ease) {
        this.easeFunction = ease;
        return this;
    }

    public Ease easeFunction() {
        return this.easeFunction;
    }

    @Override
    public Object clone() {
        try {
            return super.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException(e);
        }
    }


    public enum RotationType {
        SERVER, CLIENT;
    }


    public enum Ease {
        //        EASE_OUT_BACK(x -> 1 + (1 + 2 * (x - 1)) * (x - 1) * (x - 1)),
        EASE_OUT_SINE(x -> (float) Math.sin((x * Math.PI) / 2)), EASE_IN_OUT_SINE(x -> (float) (-(Math.cos(x * Math.PI) - 1) / 2)), EASE_OUT_QUAD(x -> 1 - (1 - x) * (1 - x)), EASE_OUT_CUBIC(x -> 1 - (1 - x) * (1 - x) * (1 - x)), EASE_OUT_CIRC(x -> (float) Math.sqrt(1 - (x - 1) * (x - 1)));
//        EASE_OUT_MIN_JERK(x -> (float) (6 * Math.pow(x, 5) - 15 * Math.pow(x, 4) + 10 * Math.pow(x, 3)));
        private final Function<Float, Float> easingFunction;

        Ease(Function<Float, Float> easingFunction) {
            this.easingFunction = easingFunction;
        }

        public float invoke(float x) {
            return easingFunction.apply(x);
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Minecraft mc() {
        return this.mc;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Optional<Angle> from() {
        return this.from;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Optional<Angle> to() {
        return this.to;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Optional<Target> target() {
        return this.target;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Optional<Runnable> callback() {
        return this.callback;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public long time() {
        return this.time;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean easeBackToClientSide() {
        return this.easeBackToClientSide;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean followTarget() {
        return this.followTarget;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationType rotationType() {
        return this.rotationType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean randomness() {
        return this.randomness;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration from(final Optional<Angle> from) {
        this.from = from;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration to(final Optional<Angle> to) {
        this.to = to;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration target(final Optional<Target> target) {
        this.target = target;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration callback(final Optional<Runnable> callback) {
        this.callback = callback;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration time(final long time) {
        this.time = time;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration easeBackToClientSide(final boolean easeBackToClientSide) {
        this.easeBackToClientSide = easeBackToClientSide;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration followTarget(final boolean followTarget) {
        this.followTarget = followTarget;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration rotationType(final RotationType rotationType) {
        this.rotationType = rotationType;
        return this;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public RotationConfiguration randomness(final boolean randomness) {
        this.randomness = randomness;
        return this;
    }
}
