// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.util.helper;

import com.vertexai.util.AngleUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

public class Target {
    private Vec3 vec;
    private Entity entity;
    private BlockPos blockPos;
    private Angle angle;
    private float additionalY = (float) (1 + Math.random()) * 0.75F;

    public Target(Vec3 vec) {
        this.vec = vec;
    }

    public Target(Entity entity) {
        this.entity = entity;
    }

    public Target(BlockPos blockPos) {
        this.blockPos = blockPos;
    }

    public Target(Angle angle) {
        this.angle = angle;
    }

    // Ensures Rotation Always Ends
    public Angle getTargetAngle() {
        if (blockPos != null) {
            return AngleUtil.getRotation(blockPos);
        }
        if (vec != null) {
            return AngleUtil.getRotation(vec);
        }
        if (entity != null) {
            return AngleUtil.getRotation(entity.position().add(0, additionalY, 0));
        }
        return angle;
    }

    @Override
    public String toString() {
        return "Vec3: " + this.vec + ", Ent: " + (this.entity != null ? this.entity.getId() : "null") + ", Pos: " + this.blockPos + ", Angle: " + this.angle;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Entity getEntity() {
        return this.entity;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public BlockPos getBlockPos() {
        return this.blockPos;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Angle getAngle() {
        return this.angle;
    }

    /**
     * @return {@code this}.
     */
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Target additionalY(final float additionalY) {
        this.additionalY = additionalY;
        return this;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public float additionalY() {
        return this.additionalY;
    }
}
