// Generated by delombok at Sat Jul 18 18:52:05 EDT 2026
package com.vertexai.feature.impl.AutoGetStats.tasks;

/**
 * An abstract task class with a generic type parameter representing the result type.
 * <p>
 * Each task follows a lifecycle with {@code init()}, {@code onTick()}, and {@code end()} methods.
 * The task begins in a {@link TaskStatus#PENDING} state by default
 * Subclasses must implement {@code getResult()} to return the final output once the task is complete.
 * <p>
 * In the subclass, please initialize taskStatus to {@link TaskStatus#RUNNING}. Once the task has successfully finished,
 * set it to{@link TaskStatus#SUCCESS}. If the task failed, set taskStatus to {@link TaskStatus#FAILURE}, and attach
 * an error.
 *
 * @param <T> the type of result this task produces upon successful completion
 */
public abstract class AbstractInventoryTask<T> {
    protected TaskStatus taskStatus = TaskStatus.PENDING;
    protected String error;

    public abstract void init();

    public abstract void onTick();

    public abstract void end();

    public abstract T getResult();

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public TaskStatus getTaskStatus() {
        return this.taskStatus;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getError() {
        return this.error;
    }
}
